### ISSUE TITLE
DNS resolution issues still occur in 2.21.0

### ISSUE THREAD

**Issue by ssplatt** [aws/aws-for-fluent-bit#253]
Copy of issue from upstream https://github.com/fluent/fluent-bit/issues/4157

Fluent-bit 1.8.7, AWS for fluent 2.20.0.  Running in AWS Fargate using Firelens.

Datadog output does deliver some logs but drops many.

Many messages per minute like `[2021/10/04 13:56:07] [ warn] [engine] failed to flush chunk '1-1633355763.278469126.flb', retry in 10 seconds: task_id=0, input=forward.1 > output=datadog.1 (out_id=1)` followed by `[2021/10/04 13:56:17] [ warn] [engine] chunk '1-1633355763.278469126.flb' cannot be retried: task_id=0, input=forward.1 > output=datadog.1`. All of our services running fb 1.8.7/awsffb 2.20.0 are throwing this same error, in multiple environments.

cloudformation example:
```
...
        LogConfiguration:
            LogDriver: awsfirelens
            Options:
              Name: datadog
              TLS: 'on'
              compress: gzip
              apikey: '${DD_API_KEY}'
              dd_service: !Ref ServiceName
              dd_source: nginx
              Log_Level: warning
...
       - Name: log_router
          Image: public.ecr.aws/aws-observability/aws-for-fluent-bit:2.20.0
          Essential: true
          MemoryReservation: 50
          Secrets:
            - Name: DD_API_KEY
              ValueFrom: DdApiKey
          FirelensConfiguration:
            Type: fluentbit
            Options:
              enable-ecs-log-metadata: 'true'
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-region: !Ref AWS::Region
              awslogs-group: !Ref LogGroup
              awslogs-stream-prefix: ecs
```

I do have a lot of occurrences of `[2021/10/04 18:31:01] [ warn] [net] getaddrinfo(host='http-intake.logs.datadoghq.com', err=12): Timeout while contacting DNS servers` as well.

**Comment by ssplatt** [comment]
CFN has been updated to use the LogConfiguration SecretOptions but the issue persists.

**Comment by PettitWesley** [comment]
Saw a report of DNS issues with 2.20.0 and ES and CW outputs: https://github.com/aws/aws-for-fluent-bit/issues/235#issuecomment-935251586

**Comment by ssplatt** [comment]
i pushed a change to all my services to increase their memory but I haven't seen any change in memory use or in the amount of errors produced. So I don't think a memory limit or OOM killer is the issue.

**Comment by zhonghui12** [comment]
Hi @ssplatt, I tried to reproduce the DNS issue on my side but failed. It seems my task goes well. I ran it several times and I saw this error log once but then it was retried and no more warning:
`[2021/10/20 23:16:39] [ warn] [engine] failed to flush chunk '1-1634771796.18542375.flb', retry in 6 seconds: task_id=0, input=forward.1 > output=datadog.1 (out_id=1)`

To be specific, here is my task definition:
```
{
    "family": "my-test-dns-issue",
    "taskRoleArn": "my-task-role-arn",
    "executionRoleArn": "my-execution-role-arn",
    "networkMode": "awsvpc",
    "requiresCompatibilities": [
        "FARGATE"
    ],
    "memory": "512",
    "cpu": "256",
    "containerDefinitions": [
        {
            "essential": true,
            "image": "public.ecr.aws/aws-observability/aws-for-fluent-bit:2.21.0",
            "name": "log_router",
            "firelensConfiguration": {
                "type": "fluentbit",
                "options":{
                    "enable-ecs-log-metadata":"true"
                }
            },
            "logConfiguration": {
                "logDriver": "awslogs",
                "options": {
                    "awslogs-group": "dns-issue-test",
                    "awslogs-region": "us-east-1",
                    "awslogs-create-group": "true",
                    "awslogs-stream-prefix": "firelens"
                }
            },
            "memoryReservation": 50
         },
         {
            "essential": true,
            "image": "nginx",
            "name": "app",
            "logConfiguration": {
                "logDriver":"awsfirelens",
                "options": {
                   "Name": "datadog",
                   "Host": "http-intake.logs.datadoghq.com",
                   "TLS": "on",
                   "dd_service": "my-test-service-dns-issue",
                   "dd_source": "nginx",
                   "dd_tags": "project:example",
                   "provider": "ecs",
                   "apikey":"my-api-key",
                   "Log_Level":"warning",
                   "compress":"gzip"
               }
           }
        }
    ]
}
```

I am not sure if the issue is related to the env/config setup. So could you please try run in a different/clean env to see if the DNS issue still exists? I am not sure if there is a real bug in the upstream code about it. And there is one more option you could try with DNS to resolve the issue: `"net.dns.mode":"UDP"`or `"net.dns.mode":"TCP"`.

**Comment by ssplatt** [comment]
Would running in us-east-1 be part of the problem? I have this error in 8 different applications, deployed across 3 different VPCs (environments), so 24 deployments in total. I guess if it's not a datadog issue, or fluent bit issue, then it could be a VPC dns issue? But I also have fluentd deployed which we were hoping to phase out which does not have this problem.

**Comment by ssplatt** [comment]
I haven't tried the tcp or udp setting yet, Ill try that tomorrow. We do have a support relationship with aws so I'll open a ticket to see if they can help track down a dns issue in our VPCs. And we are also running many datadog agent containers. Actually each one of these applications has both a datadog agent and a fluent but side car. The datadog agent handles metrics and apm. I don't believe we are having any DNS issues with the datadog agents.

**Comment by JohnPreston** [comment]
Giving a 2022 update: still seeing that error coming out, with the destination being firehose. However, data does make it to firehose so unsure what's happening there.
